version: 1.0.{build}
image: Visual Studio 2017

install:
  # Install Windows Phone 7.1 SDK if needed
  - choco install wp71sdk -y

build:
  project: Windows-Phone-7.1-Expense-Tracker-App.sln
  verbosity: minimal
  publish_wap: false

platform: Any CPU
configuration: Release